/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef NOWKDI_PRIVATE_H
#define NOWKDI_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"-1111.-11111.-2222.-666"
#define VER_MAJOR	-1111
#define VER_MINOR	-11111
#define VER_RELEASE	-2222
#define VER_BUILD	-666
#define COMPANY_NAME	"WINDOWS 11 GDI AND TOM"
#define FILE_VERSION	"-1111.-11111.-2222.-666"
#define FILE_DESCRIPTION	"BEST GDI MALWARE SETUP"
#define INTERNAL_NAME	"NOWKDI.EXE MALWARE"
#define LEGAL_COPYRIGHT	"WINDOWS 11 GDI AND TOM"
#define LEGAL_TRADEMARKS	"WINDOWS 11 GDI AND TOM"
#define ORIGINAL_FILENAME	"NOWKDI.EXE MALWARE"
#define PRODUCT_NAME	"NOWKDI.EXE MALWARE"
#define PRODUCT_VERSION	"-1111.-11111.-2222.-666"

#endif /*NOWKDI_PRIVATE_H*/
