#pragma once

#include "main.h";

DWORD WINAPI firstPayload(LPVOID lpParam);
DWORD WINAPI stretch(LPVOID lpParam);
DWORD WINAPI xWaves(LPVOID lpParam);
DWORD WINAPI hueNoShift(LPVOID lpParam);
DWORD WINAPI SquaresRGB(LPVOID lpParam);
DWORD WINAPI thirdPayload(LPVOID lpParam);
DWORD WINAPI shapesPayload(LPVOID lpParam);
DWORD WINAPI circlePayload(LPVOID lpParam);
DWORD WINAPI invert(LPVOID lpParam);
DWORD WINAPI waves(LPVOID lpParam);
DWORD WINAPI highWaves(LPVOID lpParam);
DWORD WINAPI cube(LPVOID lpParam);
DWORD WINAPI hueCircle(LPVOID lpParam);
DWORD WINAPI cubes(LPVOID lpParam);
DWORD WINAPI colorShift(LPVOID lpParam);
DWORD WINAPI colorShift2(LPVOID lpParam);
DWORD WINAPI brightWaves(LPVOID lpParam);
DWORD WINAPI wavesBall(LPVOID lpParam);
DWORD WINAPI Shake(LPVOID lpParam);
DWORD WINAPI colorCubes(LPVOID lpParam);
DWORD WINAPI hueCircle2(LPVOID lpParam);
DWORD WINAPI dizzy1(LPVOID lpParam);
DWORD WINAPI Squares(LPVOID lpParam);
DWORD WINAPI dizzy2(LPVOID lpParam);
DWORD WINAPI paintRectangles(LPVOID lpParam);
DWORD WINAPI patInvert(LPVOID lpParam);
DWORD WINAPI pixelShift(LPVOID lpParam);
DWORD WINAPI invertRectangles(LPVOID lpParam);
DWORD WINAPI colorRectangles(LPVOID lpParam);
DWORD WINAPI cubes2(LPVOID lpParam);
DWORD WINAPI yellow(LPVOID lpParam);
DWORD WINAPI lastShader(LPVOID lpParam);
DWORD WINAPI dizzy3(LPVOID lpParam);
DWORD WINAPI lastWaves(LPVOID lpParam);
DWORD WINAPI lastSineWaves(LPVOID lpParam);
DWORD WINAPI lastBrightWaves(LPVOID lpParam);
DWORD WINAPI goodCubes(LPVOID lpParam);
DWORD WINAPI circle(LPVOID lpParam);
DWORD WINAPI coloredPixels(LPVOID lpParam);
DWORD WINAPI cubesCurcle(LPVOID lpParam);
DWORD WINAPI white(LPVOID lpParam);
DWORD WINAPI colors(LPVOID lpParam);